Onboarding document
kumarsi/hygieia-setup pull request #10
Opened 2020-03-16 14:05 UTC by namankrs

Will update remaining after getting EUID and laptop setup done.

2020-03-18 10:36 UTC, kumarsi requested changes
The README links have already been made on master, you may want to rebase once again.

2020-03-18 10:36 UTC, kumarsi commented on ONBOARDING.md
> +- Get your TW-associated id to the trello wall "metrics-dashboard"
Link to Trello wall

2020-03-18 10:36 UTC, kumarsi commented on ONBOARDING.md
> +- Get your TW github Id added to [tw-hygieia](https://github.com/tw-hygieia)
Give the github teams link

2020-03-18 10:57 UTC, namankrs commented
Changes incorporated

2020-03-19 04:37 UTC, kumarsi approved these changes

2020-03-19 04:37 UTC, merged